### PR TITLE
FEAT: Support Python 3.10

### PR DESCRIPTION
**Pull request by madpah**
As per #60.

### CODE REVIEW

**Review by jkowalleck — APPROVED** [review]

**Comment by jkowalleck** [comment]
@madpah could you change the `from None` in the exception raises? 

if you want to forward the original exception (which is usually the case p there is no real reason to not do it) then just add it.
example change
```patch
< except StopIteration as err:
<             raise JSONDecodeError("Expecting value", s, err.value) from None
> except StopIteration as err:
>             raise JSONDecodeError("Expecting value", s, err.value) from err
``` 

if you want to omitt the original error, then this example would work
```patch
< except StopIteration as err:
<             raise JSONDecodeError("Expecting value", s, err.value) from None
> except StopIteration as err:
>             raise JSONDecodeError("Expecting value", s, err.value)
```

**Review by jkowalleck — DISMISSED** [review]
fix invalid py syintax as described here: https://github.com/CycloneDX/cyclonedx-python-lib/pull/64#issuecomment-965040741

**Comment by madpah** [comment]
> https://github.com/CycloneDX/cyclonedx-python-lib/runs/4163052097?check_suite_focus=true#step:9:43

These errors are not from this libraries code I don't think @jkowalleck - I think they are from the JSON library itself??

**Comment by madpah** [comment]
We are suffering from https://github.com/python-poetry/poetry/issues/4210 it seems - issues with Poetry and Python 3.10.

Will attempt the stated workaround.

**Pull request merged**
