### PR TITLE
fix: properly sort components based on all properties

### LINKED ISSUE #586: The Component `__lt__` function can result in invalid components SortedSet
Since the __lt__ function only compares type, group, name, version, the components SortedSet can have their ordering violated
This violates the constraints that containers use to track their elements.

Since adding or removing items from the sorted set will only be ordered based on the __lt__ operator, items that have the same type/group/name/version are not ordered deterministically. this can result in checks for __contains__ to pass for ._set but fail for _list.

An example use case is when an SBOM has multiple components that have the same type, group, name, and version, but DIFFERENT qualifiers etc..

The solution just requires updating the __lt__ function to include additional criteria including the purl, cpe, etc...

An additional side-effect of the current __lt__ operation is that the contents produced from the exact same code can produce different outputs.

### LINKED ISSUE #598: BUG: arbitrary dict comparison causes issues
dict comparison causes issues.

this is new in v7.3.1, did not happen with v7.3.0

```text
  

  File "/.../.venv/lib/python3.11/site-packages/sortedcontainers/sortedset.py", line 359, in add
    self._list.add(value)
  File "/.../.venv/lib/python3.11/site-packages/sortedcontainers/sortedlist.py", line 279, in add
    insort(_lists[pos], value)
  File "/.../.venv/lib/python3.11/site-packages/cyclonedx/model/component.py", line 1701, in __lt__
    return _ComparableTuple((
           ^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.11/site-packages/cyclonedx/_internal/compare.py", line 41, in __lt__
    return True if s < o else False
                   ^^^^^
TypeError: '<' not supported between instances of 'dict' and 'dict'
CRITICAL | CDX > '<' not supported between instances of 'dict' and 'dict'
```

v7.3.1 introduced a feature, and hide it as a bug fix ... 
anyway, the v7.3.1 SHOULD be yanked, and a fixed version must be released.

### PR DESCRIPTION
**Pull request by jkowalleck**
reverts #587 - as this one introduced errors
fixes #598
fixes #586

### CODE REVIEW

**Comment by jkowalleck** [comment]
@madpah please review

**Review by madpah — APPROVED** [review]

**Comment by madpah** [comment]
Code looks good @jkowalleck - but some tests failing to run - seems to be GitHub related??

**Comment by madpah** [comment]
```
Error: dyld[3646]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    Referenced from: <09857011-94D0-3FBA-9F9D-9FCE0E7366FF> /Users/runner/hostedtoolcache/Python/3.10.14/x64/bin/python3.10
    Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/
  Error: libintl.8.dylib' (no such file, not in dyld cache)
  ./setup.sh: line 52:  3646 Abort trap: 6           ./python -m ensurepip
  Error: The process '/bin/bash' failed with exit code 134
```

**Comment by madpah** [comment]
Looks to be related to GitHub having changed the version of MacOSX associated with `macos-latest` OS that we refer to.

Previously this pointed to:
```
Current runner version: '2.315.0'
Operating System: macOS 12.7.4 21H1123
```

Now it points to:
```
Current runner version: '2.316.0'
Operating System: macOS 14.4.1 23E224
Image: macos-14-arm64
```

And the new runner image only has support for Python 3.11 & 3.12 - see [here](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#python)

**Comment by madpah** [comment]
CI running for MacOSX now @jkowalleck - but Codacy has an alert

**Pull request merged**
