### PR TITLE
Allow serializing of patch resolves items for xml

### LINKED ISSUE #313: The resolves entries of a Patch object are not serialized to XML
When a BOM is created that has Patch objects with a non empty resolves property, the Issues are ignored and do not appear in the output.

The resolves property stored in a ReleaseNote object is already correctly serialized, so it is just a matter of some code reuse.

See: 
https://github.com/CycloneDX/cyclonedx-python-lib/pull/312 for a patch and test.

### PR DESCRIPTION
**Pull request by schlenk**
Add the necessary parts to serialize the resolves part of patches to XML.

fixes #313

### CODE REVIEW

**Comment by jkowalleck** [comment]
i dont see any tests.

**Comment by schlenk** [comment]
I'll give it a try.

**Comment by jkowalleck** [comment]
please be aware that there is currently a feature stop while v4 is in the making.
see https://github.com/CycloneDX/cyclonedx-python-lib/milestone/4
see https://github.com/CycloneDX/cyclonedx-python-lib/pull/262

this means your feature might not be merged before v4 was drafted.
:zap: I would advice you to open an issue describing the feature you try to implement. 
we then can discuss how the implementation process can be done in a coordinated way.

**Comment by schlenk** [comment]
That is okay. 
The patch will actually become smaller, as the serialization for issues is already there (just inside the release_notes, not for patches), noticed it while trying to write a test. So its basically is just a bit of code reuse.

**Comment by jkowalleck** [comment]
any updates?

**Comment by schlenk** [comment]
This seems to be fixed and obsolete with the new serialization since 4.0.

**Pull request closed without merging**
