### PR TITLE
Converting properties list to a string before it is input into `hash`.

### PR DESCRIPTION
**Pull request by 0t1s1**
Resolved isssue #153 .

Signed-off-by: Aaron Otis <otis1@llnl.gov>

### CODE REVIEW

**Review by jkowalleck — CHANGES_REQUESTED** [review]
i dont like the the proposed fox for #153 for the following reasons: 
converting an object to string does not solve the problem.

is there a reason why the classes that currently fail hashing should not have a `__hash__()` implemented?

**Comment by 0t1s1** [comment]
The classes that are currently failing to hash are lists, which do not have `__hash__()` implemented because they are mutable. I agree that the purposed fix isn't the best, I just copied what was [already being done](https://github.com/CycloneDX/cyclonedx-python-lib/blob/dec63de950e0ad81cbb51373b0e647bce551297e/cyclonedx/model/component.py#L493-L494) for the other three lists stored in the object. Converting the lists to strings is not a solution as identical `Component` objects will not be evaluated as equal if the underlying lists are in different orders.

I was considering opening a different PR to address this, but if you like we can tackle it in this one.

**Comment by madpah** [comment]
Thanks for the PR @0t1s1 - but we already have a proper solution (we hope) in #148 if you care to take a look there and provide any feedback?

**Comment by 0t1s1** [comment]
Thanks @madpah. I took a brief look at #148 and it looks fine to me. Do you want me to close this PR?

**Comment by madpah** [comment]
If you're happy to close this PR @0t1s1, that would be helpful.

Thanks for calling this out - we're hoping to get `2.0.0` released next week which includes this update.

**Pull request closed without merging**
