### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by rolweber**
noticed while reading the docs

### CODE REVIEW

**Comment by jkowalleck** [comment]
thank you for the fix, @rolweber .

i would love to merge it, but i need your consent to publish your work under the license of this project.
therefore, please sign your commit.
Please follow the instructions: <https://github.com/CycloneDX/cyclonedx-python-lib/pull/318/checks?check_run_id=10085359274>

**Comment by rolweber** [comment]
Grmpf. Signing isn't enough, I also need to mention in the commit message that it's signed :-?

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/cyclonedx-python-lib/pull/318#issuecomment-1350722019
exactly. for legal reasons each commit needs to ne signed-off to indicate that the author acknowledged the projects license and puts their work under said license.

This process is not regarding signed identity but legal signature.
You can read more here: 
* https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CONTRIBUTING.md#sign-your-commits

**Comment by rolweber** [comment]
I fell for the difference between `-S` and `-s`.

**Comment by rolweber** [comment]
All checks are passing now.

**Review by jkowalleck — APPROVED** [review]

**Pull request merged**
