### PR TITLE
fix: serialization of `model.component.Diff`

### LINKED ISSUE #556: class `Diff` is not serializable
[Gist with example code reproducing the issue.](https://gist.github.com/rcross-lc/9ea2336a810281307cb1e638b8ac398e)

Expected output:

```
...
"patches": [
  {
    "diff": {
      "url": "https://en.wikipedia.org/wiki/Diff"
    },
    "type": "backport"
  }
]
...
```

Actual output: 
```
...
"patches": [
  {
    "diff": "<Diff url=https://en.wikipedia.org/wiki/Diff>",
    "type": "backport"
  }
]
...
```

The example also fails to deserialize the json as well.

### PR DESCRIPTION
**Pull request by rcross-lc**
This seems to fix #556 for me locally, but some tests should probably be added as well.

### CODE REVIEW

**Comment by jkowalleck** [comment]
great. thank you for the report and the quick fix.

could you add test cases for this? 
just add new function(s) like `def get_bom_<some_usecase_>_valid() -> Bom:` to https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/tests/_data/models.py, and run `CDX_TEST_RECREATE_SNAPSHOTS=1 poetry run tox -e py` to generate the test result snapshots.

**Comment by rcross-lc** [comment]
Sure, I'll try and get to it tonight if I can.

**Comment by jkowalleck** [comment]
DO you need assistance, @rcross-lc ?

**Comment by jkowalleck** [comment]
> could you add test cases for this?

- [x] add test cases -- via https://github.com/CycloneDX/cyclonedx-python-lib/pull/557/commits/d65ca234056ea3241c4a1d54cee9ccdcec71a685

**Pull request merged**
