### PR TITLE
feat: add workaround property for v1.5 and v1.6

### PR DESCRIPTION
**Pull request by loulou123546**
Property `workaround` was missing from the vulnerability model. It was added in spec v1.5 and was marked as TODO before.

This is my first contribution on this project so if I done something wrong, just say me :smiley:

### CODE REVIEW

**Comment by jkowalleck** [comment]
@loulou123546 , 
Could you rebase on latest master and fix the conflicts.
I had to do some style-changes(#643) to make the review easier.
Sorry for the inconvenience.

**Comment by loulou123546** [comment]
Resolved conflict, and no problem, it's much nicer to read now :)

**Review by jkowalleck — APPROVED** [review]

**Comment by jkowalleck** [comment]
thank you for the contribution, @loulou123546 .

CycloneDX py-lib is a community effort. Whenever you anything missing or in need of improvement, feel free to open an issue describing the needs.
In cases of known TODOs - like this one - a PR is enough. :+1:

**Comment by jkowalleck** [comment]
this enhancement was released via v7.5.0

**Pull request merged**
